FROM golang:1.24.1-alpine AS build
WORKDIR /derper

ARG DERP_VERSION=latest
RUN go install tailscale.com/cmd/derper@${DERP_VERSION}


FROM alpine:3.21.3
WORKDIR /derper

ENV DERP_ACCEPT_CONNECTION_BURST=9223372036854775807
ENV DERP_ACCEPT_CONNECTION_LIMIT=+Inf
ENV DERP_ADDR="0.0.0.0:443"
ENV DERP_BOOTSTRAP_DNS_NAMES=""
ENV DERP_CERT_DIR="/derper/certs"
ENV DERP_CERT_MODE=letsencrypt
ENV DERP_CONFIG_FILE="/derper/config.json"
ENV DERP_DERP_ENABLE=true
ENV DERP_DEV_MODE=false
ENV DERP_HOME_PAGE="blank"
ENV DERP_HOSTNAME="example.com"
ENV DERP_HTTP_PORT=80
ENV DERP_MESH_PSK_FILE=""
ENV DERP_MESH_WITH=""
ENV DERP_SECRETS_CACHE_DIR="/derper/cache/derper-secrets"
ENV DERP_SECRETS_PATH_PREFIX="prod/derp"
ENV DERP_SECRETS_URL=""
ENV DERP_SOCKET=""
ENV DERP_STUN_ENABLE=true
ENV DERP_STUN_PORT=3478
ENV DERP_TCP_KEEPALIVE_TIME="10m0s"
ENV DERP_TCP_USER_TIMEOUT="15s"
ENV DERP_TCP_WRITE_TIMEOUT="2s"
ENV DERP_UNPUBLISHED_BOOTSTRAP_DNS_NAMES=""
ENV DERP_VERIFY_CLIENTS=false
ENV DERP_VERIFY_CLIENT_URL=""
ENV DERP_VERIFY_CLIENT_URL_FAIL_OPEN=true

RUN mkdir /derper/{certs,cache,keys}

COPY --from=build /go/bin/derper .
COPY ./entrypoint.sh /

ENTRYPOINT sh /entrypoint.sh
